[package]
name = "fuzzydate"
description = "A flexible date parsing library"
version = "0.2.2"
edition = "2021"
authors = ["Abhay Agarwal"]

[dependencies]
chrono = "0.4"
lazy_static = "1.4"
thiserror = "1.0"

[dev-dependencies]
test-case = "3.3.1"
